http:
  port: 3001
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth-api:
    host: localhost
    paths: '/api/v1/*'
  scolarite-api:
    host: localhost
    paths: '/api/v2/*'  
serviceEndpoints:
  auth-service:
    url: 'http://localhost:8000'
  scolarite-service:
    url : 'http://localhost:8002'  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - auth-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: auth-service 
              changeOrigin: true
