http:
  port: ${PORT:-8080}
admin:
  port: ${PORT:-9876}
  host: localhost
apiEndpoints:
  auth-api:
    host: localhost
    paths: '/api/v1/*'
  scolarite-api:
    host: localhost
    paths: '/api/v2/*'  
  notes-api:
    host: localhost
    paths: '/api/v3/*'    
serviceEndpoints:
  auth-service:
    url: 'https://immense-caverns-54916.herokuapp.com'
  scolarite-service:
    url : 'https://peaceful-gorge-36360.herokuapp.com' 
  notes-service:
    url : 'https://obscure-refuge-89278.herokuapp.com'  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - auth-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: auth-service 
              changeOrigin: true
  pipeline1:
    apiEndpoints:
      - scolarite-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: scolarite-service
              changeOrigin: true
  pipeline2:
      apiEndpoints:
        - notes-api
      policies:
        - proxy:
            - action:
                serviceEndpoint: notes-service
                changeOrigin: true              
